### ISSUE TITLE
Exception on reload

### ISSUE THREAD

**Issue by p82183645** [OsipXD/RPGInventory#158]
```
issued server command: /rpginv reload
[09:35:13] [Server thread/INFO]: [RPGInventory] Disabling RPGInventory v2.1.6
[09:35:13] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder hook for placeholder: rpginv
[09:35:13] [Server thread/INFO]: [RPGInventory] Saving players inventories...
[09:35:13] [Server thread/INFO]: [RPGInventory] Enabling RPGInventory v2.1.6
[09:35:13] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader RPGInventory v2.1.6
[09:35:14] [Server thread/ERROR]: Error occurred while enabling RPGInventory v2.1.6 (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_131]
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:1.8.0_131]
	at ru.endlesscode.rpginventory.misc.FileLanguage.validateLocaleFile(FileLanguage.java:145) ~[?:?]
	at ru.endlesscode.rpginventory.misc.FileLanguage.<init>(FileLanguage.java:53) ~[?:?]
	at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:128) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1437]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1437]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1437]
	at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.reloadPlugin(RPGInventoryCommandExecutor.java:251) ~[?:?]
	at ru.endlesscode.rpginventory.RPGInventoryCommandExecutor.onCommand(RPGInventoryCommandExecutor.java:207) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1437]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1437]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1437]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1437]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[09:35:14] [Server thread/INFO]: [RPGInventory] Disabling RPGInventory v2.1.6
[09:35:14] [Server thread/INFO]: [RPGInventory] Saving players inventories...
```

**Environment:**
 - Server Core: Paper
 - Server Version: 1.12.2
 - Plugin Version: 2.1.6

**Comment by osipxd** [comment]
For work.
https://github.com/EndlessCodeGroup/RPGInventory/blob/c0a62cf70c6c8286127d1b4170d6786d1a0dd4fb/src/main/java/ru/endlesscode/rpginventory/misc/FileLanguage.java#L144-L146
Looks like `this.plugin.getResource("lang/en.lang")` is null.

**Comment by Dereku** [comment]
But it's can not be null. Also, if there is no error on startup, so we have a *magic* NPE.
