### ISSUE TITLE
Players get double attributes

### ISSUE THREAD

**Issue by AaronHzy** [OsipXD/RPGInventory#160]
**Prerequisites**
* [x] Are you running the latest version?
* [x] Did you check the FAQs on [plugin's page](https://www.spigotmc.org/resources/12498/)?
* [x] Did you check the [Wiki](http://rpginventory.endlesscode.ru/)?
* [x] Did you configure [config.yml](https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/resources/config.yml)?
* [x] Did you perform a cursory search?
* [x] Can you reproduce the problem on clean server (with installed only the plugin and dependencies)?

**Describe the bug**
When I put the weapon to the weapon slot
Players have 11 damage
When switching to the hand, Players have 22 damage

**To Reproduce**
1. Put the weapon to the weapon slot
2. Switching to the hand
3. Get double attributes

**Screenshots or video**
https://s1.ax1x.com/2018/06/11/CL8ab4.png
https://s1.ax1x.com/2018/06/11/CL8wVJ.png

**Environment:**
 - Server Core: PaperSpigot-1.12.2-b1409
 - Server Version: 1.12.2
 - Plugin Version: 2.1.6
 - DivineItemsRPG 3.2.5

**Comment by osipxd** [comment]
Ok, I've put default sword to weapon slot (followed all your steps) and nothing happens.

**Comment by AaronHzy** [comment]
YES，I tested is  BUG in DivineItemsRPG 3.2.5
but have a new bug

When I put the weapon to the weapon slot
drop(Q) in protected area
Weapon disappear

**Comment by osipxd** [comment]
It should be an item created in RPGInv or in DivineItemsRPG?
What is protected area? Private WorldGuard region?

**Comment by AaronHzy** [comment]
YES Private WorldGuard region
and have a error ，lead to server crashes

```
[19:50:25 INFO]: Killer issued server command: /rpginv open
[19:50:28 ERROR]: Could not pass event EntityDamageByEntityEvent to RPGInventory v2.1.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B(EntityWolf.java:236) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
```

**Comment by osipxd** [comment]
@AaronHzy, it is full error?

**Comment by AaronHzy** [comment]
Yes Repeatedly 

```
[10:26:45 ERROR]: Could not pass event EntityDamageByEntityEvent to RPGInventory v2.1.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:853) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B(EntityWolf.java:236) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
[10:26:47 ERROR]: Could not pass event EntityDamageByEntityEvent to RPGInventory v2.1.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:94) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:581) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:484) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:613) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1369) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity0(EntityHuman.java:853) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:887) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:612) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B(EntityWolf.java:236) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:677) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2123) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:508) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1976) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:247) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1771) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1741) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1409.jar:git-Paper-1409]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
```

**Comment by osipxd** [comment]
Have you tried to use snapshot?

**Comment by AaronHzy** [comment]
No , Where?

**Comment by osipxd** [comment]
On Discord #russian channel
