### ISSUE TITLE
java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by Caishangqi** [OsipXD/RPGInventory#173]
When I use  RPGInventory v2.4.0-rc1 with MMOItems-6.6.0, I need to click the inventory button to refresh the item attribute that applies to the player. Besides, there are zip files closed when /rpgreload
Server Version: Paper 1.17.1
Java Version: 16.0.2
Error Log https://paste.ubuntu.com/p/HzfJprcSqX/

**Comment by osipxd** [comment]
Thank you for your report. I haven't enough time to work on the plugin but maybe somebody else will fix this bug faster than I.

**Comment by Caishangqi** [comment]
> Thank you for your report. I haven't enough time to work on the plugin but maybe somebody else will fix this bug faster than I.

Thanks for the replies!

**Comment by osipxd** [comment]
Another stacktrace
```java
Could not pass event PlayerItemHeldEvent to RPGInventory v2.3.2
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.report.SentryReporter.report(SentryReporter.kt:63) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.report.BukkitUnwrapReporter.report(BukkitUnwrapReporter.kt:15) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.report.BukkitUnwrapReporter.report(BukkitUnwrapReporter.kt:11) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager.trackEvent(TrackedPluginManager.kt:126) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager.access$trackEvent(TrackedPluginManager.kt:13) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager$wrapRegisteredListener$1.callEvent(TrackedPluginManager.kt:89) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2004) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:24) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:7) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1455) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"9f3435b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by osipxd** [comment]
And another one:
```java
Could not pass event PlayerItemHeldEvent to RPGInventory v2.4.0-rc1
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:519) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:166) ~[patched_1.16.5.jar:git-Purpur-1126]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Purpur-1126]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1126]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.report.SentryReporter.report(SentryReporter.kt:50) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.report.BukkitUnwrapReporter.report(BukkitUnwrapReporter.kt:15) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.report.BukkitUnwrapReporter.report(BukkitUnwrapReporter.kt:11) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager.trackEvent(TrackedPluginManager.kt:121) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager.access$trackEvent(TrackedPluginManager.kt:11) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPluginManager$wrapRegisteredListener$1.callEvent(TrackedPluginManager.kt:84) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2043) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:24) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:7) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1331) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1307) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1151) ~[patched_1.16.5.jar:git-Purpur-1126]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1126]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Caishangqi** [comment]
The server-core i used.
https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/202/downloads/paper-1.17.1-202.jar
