### ISSUE TITLE
Update Mimic integration to 0.8

### ISSUE THREAD

**Issue by osipxd** [OsipXD/RPGInventory#178]
Mimic 0.7 contains breaking changes, so I should update RPGInventory to make it compatible with new Mimic.

```
Error occurred while enabling RPGInventory v2.4.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Found interface ru.endlesscode.mimic.level.BukkitLevelSystem$Provider, but class was expected
    at ru.endlesscode.rpginventory.RPGInventory.initMimicSystems(RPGInventory.java:182) ~[rpginventory-2.4.0-all (1).jar:?]
    at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:142) ~[rpginventory-2.4.0-all (1).jar:?]
    at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:169) ~[rpginventory-2.4.0-all (1).jar:?]
    at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:168) ~[rpginventory-2.4.0-all (1).jar:?]
    at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.0-all (1).jar:?]
    at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onEnable(TrackedPlugin.kt:168) ~[rpginventory-2.4.0-all (1).jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
```

**Comment by osipxd** [comment]
Also implement PlayerInventory API
