### ISSUE TITLE
Add 1.19.3+ support

### ISSUE THREAD

**Issue by Hahaa13** [OsipXD/RPGInventory#186]
nice a plugin
please update

**Comment by osipxd** [comment]
Thanks for the issue.
Can you describe problems you faced with the plugin on 1.19?

**Comment by osipxd** [comment]
```
Error occurred while enabling RPGInventory v2.4.1 (Is it up to date?)
java.lang.AbstractMethodError: Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
at ru.endlesscode.rpginventory.RPGInventory.getPluginMeta(RPGInventory.java) ~[rpginventory-2.4.1-all.jar:?]
at org.bukkit.plugin.PluginBase.getName(PluginBase.java:34) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.Timings.ofSafe(Timings.java:281) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448] 
at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:109) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.<init>(CraftTask.java:79) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:156) ~[rpginventory-2.4.1-all.jar:?]
at ru.endlesscode.rpginventory.RPGInventory.loadModules(RPGInventory.java:223) ~[rpginventory-2.4.1-all.jar:?]
at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:150) ~[rpginventory-2.4.1-all.jar:?]
at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:169) ~[rpginventory-2.4.1-all.jar:?]
at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.1-all.jar:?]
at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onEnable(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-448]
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-448]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-448]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-448]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-448]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[INFO] .... [RPGInventory] Disabling RPGInventory v2.4.1
```

**Comment by romandibule** [comment]
The latest version of the plugin (2.4.1) won't load on paper-1.19.4-490.jar
```
[22:32:51 INFO]: [RPGInventory] Enabling RPGInventory v2.4.1
[22:32:51 INFO]: [RPGInventory] Level system 'mmocore' found.
[22:32:51 INFO]: [RPGInventory] Class system 'mmocore' found.
[22:32:51 INFO]: [PlaceholderAPI] Successfully registered expansion: rpginv [1.0]
[22:32:51 INFO]: [RPGInventory] Placeholder API hooked!
[22:32:51 WARN]: [RPGInventory] This version of RPG Inventory is not tested with "1.19.4-R0.1-SNAPSHOT"!
[22:32:51 INFO]: [RPGInventory] Permissions hooked: LuckPerms
[22:32:51 INFO]: [RPGInventory] Economy hooked: EssentialsX Economy
[22:32:51 INFO]: [RPGInventory] 6 pet(s) has been loaded
[22:32:51 INFO]: [RPGInventory] 1 food(s) has been loaded
[22:32:51 ERROR]: Error occurred while enabling RPGInventory v2.4.1 (Is it up to date?)
java.lang.AbstractMethodError: Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
        at ru.endlesscode.rpginventory.RPGInventory.getPluginMeta(RPGInventory.java) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.PluginBase.getName(PluginBase.java:34) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.Timings.ofSafe(Timings.java:322) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-490]
        at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:110) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.<init>(CraftTask.java:79) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:156) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.loadModules(RPGInventory.java:223) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:150) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:169) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onEnable(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-490]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-490]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-490]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-490]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-490]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-490]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-490]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-490]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:32:51 INFO]: [RPGInventory] Disabling RPGInventory v2.4.1
[
```
