### ISSUE TITLE
plz add 1.19.4 support

### ISSUE THREAD

**Issue by Yurium7** [OsipXD/RPGInventory#188]
plugin cant run in purpur 1.19.4

[19:38:55 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'rpginventory-2.4.1-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: ru/endlesscode/mimic/items/BukkitItemsRegistry
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: ru/endlesscode/mimic/items/BukkitItemsRegistry
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.<init>(TrackedPlugin.kt:53) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventoryPlugin.<init>(RPGInventoryPlugin.java:40) ~[rpginventory-2.4.1-all.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: ru.endlesscode.mimic.items.BukkitItemsRegistry
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.<init>(TrackedPlugin.kt:53) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventoryPlugin.<init>(RPGInventoryPlugin.java:40) ~[rpginventory-2.4.1-all.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.19.4.jar:git-Purpur-1985]
        ... 9 more

**Comment by Yurium7** [comment]
[19:41:58 INFO]: [RPGInventory] Loading server plugin RPGInventory v2.4.1
[19:41:58 WARN]: [Mimic] Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
java.lang.AbstractMethodError: Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
        at ru.endlesscode.rpginventory.RPGInventory.getPluginMeta(RPGInventory.java) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.PluginBase.getName(PluginBase.java:34) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at ru.endlesscode.mimic.items.WrappedItemsRegistry.<init>(WrappedItemsRegistry.kt:17) ~[Mimic-v0.8.0.jar:?]
        at ru.endlesscode.mimic.MimicImpl.registerItemsRegistry(MimicImpl.kt:62) ~[Mimic-v0.8.0.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.onLoad(RPGInventory.java:134) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onLoad$1.invoke(TrackedPlugin.kt:163) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onLoad$1.invoke(TrackedPlugin.kt:162) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onLoad(TrackedPlugin.kt:162) ~[rpginventory-2.4.1-all.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:41:58 WARN]: [Mimic] Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
java.lang.AbstractMethodError: Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
        at ru.endlesscode.rpginventory.RPGInventory.getPluginMeta(RPGInventory.java) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.PluginBase.getName(PluginBase.java:34) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at ru.endlesscode.mimic.inventory.WrappedPlayerInventoryProvider.<init>(WrappedPlayerInventoryProvider.kt:17) ~[Mimic-v0.8.0.jar:?]
        at ru.endlesscode.mimic.MimicImpl.registerPlayerInventoryProvider(MimicImpl.kt:47) ~[Mimic-v0.8.0.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.onLoad(RPGInventory.java:136) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onLoad$1.invoke(TrackedPlugin.kt:163) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onLoad$1.invoke(TrackedPlugin.kt:162) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onLoad(TrackedPlugin.kt:162) ~[rpginventory-2.4.1-all.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Yurium7** [comment]
[19:42:22 ERROR]: Error occurred while enabling RPGInventory v2.4.1 (Is it up to date?)
java.lang.AbstractMethodError: Method ru/endlesscode/rpginventory/RPGInventory.getPluginMeta()Lio/papermc/paper/plugin/configuration/PluginMeta; is abstract
        at ru.endlesscode.rpginventory.RPGInventory.getPluginMeta(RPGInventory.java) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.PluginBase.getName(PluginBase.java:34) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.Timings.ofSafe(Timings.java:324) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
        at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:110) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.<init>(CraftTask.java:79) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at ru.endlesscode.rpginventory.pet.PetManager.init(PetManager.java:156) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.loadModules(RPGInventory.java:223) ~[rpginventory-2.4.1-all.jar:?]
        at ru.endlesscode.rpginventory.RPGInventory.onEnable(RPGInventory.java:150) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:169) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin$onEnable$1.invoke(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.track(TrackedPlugin.kt:191) ~[rpginventory-2.4.1-all.jar:?]
        at shade.ru.endlesscode.rpginventory.inspector.bukkit.plugin.TrackedPlugin.onEnable(TrackedPlugin.kt:168) ~[rpginventory-2.4.1-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
